import { EXPENSE_CATEGORY_SHORT_LABELS } from "@/lib/expenses";
import type { MatrixRow } from "./MonthlyMatrixTable";

export const SAAS_GROWTH_ROWS: MatrixRow[] = [
  { type: "section", label: "Income" },
  {
    type: "data",
    label: "Monthly Income",
    bold: true,
    format: "currency",
    getValue: (m) => m.totalMrr,
  },
  {
    type: "data",
    label: "Annualized Income",
    format: "currency",
    getValue: (m) => m.totalArr,
  },
  {
    type: "data",
    label: "New Monthly Income",
    format: "currency",
    getValue: (m) => m.newMrr,
  },
  {
    type: "data",
    label: "Increased Income",
    format: "currency",
    getValue: (m) => m.expansionMrr,
  },
  {
    type: "data",
    label: "Reduced Income",
    format: "currency",
    getValue: (m) => m.churnedMrr,
  },
  { type: "section", label: "Income by Source" },
  {
    type: "data",
    label: "Primary Income",
    indent: true,
    format: "currency",
    getValue: (m) => m.plgMrr,
  },
  {
    type: "data",
    label: "Secondary Income",
    indent: true,
    format: "currency",
    getValue: (m) => m.salesMrr,
  },
  {
    type: "data",
    label: "Other Income",
    indent: true,
    format: "currency",
    getValue: (m) => m.partnerMrr,
  },
  { type: "section", label: "Income Sources" },
  {
    type: "data",
    label: "Total Sources",
    bold: true,
    format: "number",
    getValue: (m) => m.totalCustomers,
  },
  {
    type: "data",
    label: "Primary Sources",
    indent: true,
    format: "number",
    getValue: (m) => m.plgCustomers,
  },
  {
    type: "data",
    label: "Secondary Sources",
    indent: true,
    format: "number",
    getValue: (m) => m.salesCustomers,
  },
  {
    type: "data",
    label: "Other Sources",
    indent: true,
    format: "number",
    getValue: (m) => m.partnerCustomers,
  },
  {
    type: "data",
    label: "Average Monthly Income",
    format: "currency",
    getValue: (m) =>
      m.totalCustomers > 0 ? m.totalMrr / m.totalCustomers : 0,
  },
];

export const SAAS_CASH_ROWS: MatrixRow[] = [
  { type: "section", label: "Cash Flow" },
  {
    type: "data",
    label: "Cash In",
    bold: true,
    format: "currency",
    getValue: (m) => m.totalCashIn,
  },
  {
    type: "data",
    label: "New Source Cash",
    indent: true,
    format: "currency",
    getValue: (m) => m.newCustomerCashIn,
  },
  {
    type: "data",
    label: "Existing Source Cash",
    indent: true,
    format: "currency",
    getValue: (m) => m.existingCustomerCashIn,
  },
  {
    type: "data",
    label: "Total Expenses",
    format: "currency",
    getValue: (m) => m.totalExpense,
  },
  {
    type: "data",
    label: "Net Cash Flow",
    bold: true,
    format: "currency",
    colorNegative: true,
    getValue: (m) => -m.netBurn,
  },
  {
    type: "data",
    label: "Cash Remaining",
    format: "currency",
    colorNegative: true,
    getValue: (m) => m.cashRemaining,
  },
];

export const FINANCIAL_ACCRUAL_ROWS: MatrixRow[] = [
  { type: "section", label: "Income" },
  {
    type: "data",
    label: "Monthly Income",
    bold: true,
    format: "currency",
    getValue: (m) => m.totalMrr,
  },
  {
    type: "data",
    label: "Direct Costs",
    format: "currency",
    getValue: (m) => m.cosExpense,
  },
  {
    type: "data",
    label: "Gross Profit",
    bold: true,
    format: "currency",
    colorNegative: true,
    getValue: (m) => m.grossProfit,
  },
  {
    type: "data",
    label: "Gross Margin",
    bold: true,
    format: "percent",
    getValue: (m) => m.grossMarginPct,
  },
  { type: "section", label: "Operating Expenses" },
  {
    type: "data",
    label: EXPENSE_CATEGORY_SHORT_LABELS.gtm,
    indent: true,
    format: "currency",
    getValue: (m) => m.gtmExpense,
  },
  {
    type: "data",
    label: EXPENSE_CATEGORY_SHORT_LABELS.rnd,
    indent: true,
    format: "currency",
    getValue: (m) => m.rndExpense,
  },
  {
    type: "data",
    label: EXPENSE_CATEGORY_SHORT_LABELS.cs,
    indent: true,
    format: "currency",
    getValue: (m) => m.csExpense,
  },
  {
    type: "data",
    label: EXPENSE_CATEGORY_SHORT_LABELS.ops,
    indent: true,
    format: "currency",
    getValue: (m) => m.opsExpense,
  },
  {
    type: "data",
    label: "Total Operating Expenses",
    bold: true,
    format: "currency",
    getValue: (m) => m.operatingExpenses,
  },
  { type: "section", label: "Operating Income" },
  {
    type: "data",
    label: "EBIT",
    bold: true,
    format: "currency",
    colorNegative: true,
    getValue: (m) => m.ebit,
  },
  {
    type: "data",
    label: "EBIT Margin",
    bold: true,
    format: "percent",
    colorNegative: true,
    getValue: (m) => m.ebitMarginPct,
  },
];

export const FINANCIAL_CASH_ROWS: MatrixRow[] = [
  { type: "section", label: "Cash Flow" },
  {
    type: "data",
    label: "Cash In",
    bold: true,
    format: "currency",
    getValue: (m) => m.totalCashIn,
  },
  {
    type: "data",
    label: "From New Sources",
    indent: true,
    format: "currency",
    getValue: (m) => m.newCustomerCashIn,
  },
  {
    type: "data",
    label: "From Existing Sources",
    indent: true,
    format: "currency",
    getValue: (m) => m.existingCustomerCashIn,
  },
  {
    type: "data",
    label: "Cash Out (Expenses)",
    format: "currency",
    getValue: (m) => m.totalExpense,
  },
  {
    type: "data",
    label: "Net Cash Flow",
    bold: true,
    format: "currency",
    colorNegative: true,
    getValue: (m) => m.totalCashIn - m.totalExpense,
  },
];
